def affine_cipher(s):
    decrypt_text = ""
    for i in s:
        decrypt_text += chr((11*(ord(i) - ord('A'))-18)%26 + ord('A'))
    return decrypt_text

print(affine_cipher("KQEREJEBCPPCJCRKIEACUZBKRVPKRBCIBQCARBJCVFCUPKRIOFKPACUZQEPBKRXPEIIEABDKPBCPFCDCCAFIEABDKPBCPFEQPKAZBKRHAIBKAPCCIBURCCDKDCCJCIDFUIXPAFFERBICZDFKABICBBENEFCUPJCVKABPCYDCCDPKBCOCPERKIVKSCPICBRKIJPKABI"))
